project:
  type: website

website:
  title: "poduval.github.io"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/rakeshkpoduval
      - icon: linkedin
        href: https://www.linkedin.com/in/poduvalrakesh/
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/Poduval/poduval.github.io

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



